version: "3.7"
services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./database.sql:/docker-entrypoint-databasedb.d/database.sql
    networks:
      - fm-network

  backend:
  container_name: friendmanagement-api
  restart: unless-stopped
  build: 
    context: .
    dockerfile: Dockerfile
    ports: 
        - "8080:8080"
    depend on: 
        - postgredb
    networks:
        - fm-network

  network: 
    fm-network:
      driver: bridge